const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
   name:{
    type:String,
    required:true,
    trim:true
   },
   description:{
    type:String,
    required:true,
   },
   price:{
    type:Number,
    required:true,
   },
   discountprice:{
    type:Number,
    
   },
   countInStock:{
    type:Number,
    required:true,
    default:0
   },
   sku:{
     type:String,
     unique:true,
     required:true,
     
   },
   category:{
      type:String,
      required:true,
   },
   brand:{
      type:String
   },
   sizes:{
      type:[String],
      required:true
   },
   colors:{
      type:[String],
      required:true
   },
   gender:{
      type:[String],
      enum:["Men","Women"]
   },
   allcollection:{
       type:String,
       required:true,
   },
   material:{
      type:String
   },
   images:[{
      url:{
         type:String,
         required:true
      },
      alText:{
         type:String
      }
   }],
   isFeatured:{
      type:Boolean,
      default:false
   },
   isPublished:{
      type:Boolean,
      default:false
   },
   rating:{
      type:Number,
      default:0
   },
   numReviews:{
      type:Number,
      default:0
   },
   tags:[String],
   user:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"User",
      required:true
   },
   metaTitle:{
      type:String,
   },
   metadesctription:{
      type:String,
   },
   metaKeyword:{
      type:String,
   },
   dimenisons:{
      length:Number,
      height:Number,
      width:Number
   },
   weight:Number
},
  {timestamps:true}
);

module.exports = mongoose.model("Product",productSchema)